suzuran: configs: Newer versions of microG's GMS core require more extensive permissions.
This prevents error messages like these:

************ Failure starting system services
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist:
{com.google.android.gms (/system/priv-app/GmsCore): android.permission.UPDATE_DEVICE_STATS,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.START_ACTIVITIES_FROM_BACKGROUND,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.LOCATION_HARDWARE,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.NETWORK_SCAN,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.MODIFY_PHONE_STATE,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.WATCH_APPOPS}

Change-Id: Ic2509248b156e7022a04f5a30903f6fc3579f67e