suzuran: configs: Newer versions of microG's GMS core require more extensive permissions.
This prevents error messages like these:

************ Failure starting system services
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist:
{com.google.android.gms (/system/priv-app/GmsCore): android.permission.PROVIDE_REMOTE_CREDENTIALS,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.PROVIDE_DEFAULT_ENABLED_CREDENTIAL_SERVICE}

Change-Id: I388d2585f79175d62c9183fdf060c3013df66471