suzuran: configs: Newer versions of microG's GMS core and FakeStore require more extensive permissions.
This prevents error messages like these:

************ Failure starting system services
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist:
{com.android.vending (/system/priv-app/FakeStore): android.permission.INSTALL_PACKAGES,
 com.android.vending (/system/priv-app/FakeStore): android.permission.INTERACT_ACROSS_USERS,
 com.google.android.gms (/system/priv-app/GmsCore): android.permission.INTERACT_ACROSS_USERS,
 com.android.vending (/system/priv-app/FakeStore): android.permission.DELETE_PACKAGES}

Change-Id: Ib82660e5b18dd3c9e45fbfc955efc19343d20477